sudo: required

services:
    - docker

before_install:
    - docker build -t manrobfer/docker-react -f Dockerfile.dev .  

script:
    - docker run -e CI=true manrobfer/docker-react npm run test -- --coverage

